### ISSUE TITLE
Option for custom start/end GCode

### ISSUE THREAD

**Issue by n0sr3v** [n0sr3v/SLAcer.js#3]
Start and end GCode should be able to be edited.

**Comment by Adukra** [comment]
Hi @n0sr3v I have coded this feature locally. If you give permissions I will push my branch and initiate pull request.

**Comment by n0sr3v** [comment]
I have granted you permissions. You could also just make a pull request.

**Comment by Adukra** [comment]
Thanks @n0sr3v . Sorry, I'm new to GitHub and I thought I had to push my branch to the repository before I could do a PR. I did the PR now but will let you review and merge.

**Comment by n0sr3v** [comment]
Tank you very much for contributing to this project!
