### ISSUE TITLE
issue if start slice with slider on  level different of 0 layer and not solid stl issue

### ISSUE THREAD

**Issue by exilaus** [n0sr3v/SLAcer.js#7]
https://drive.google.com/file/d/1Uj5AazI7MZlGHSBlgsTQ2jfGEEaVd67p/view?usp=sharing

solid stl issue resovable usign netfabb on line but see first bug if set layer slider to other level
first level are that after come reset to zero

**Comment by n0sr3v** [comment]
For now, i think there is a workaround, use: https://service.netfabb.com/service.php to fix your stl files. This works for you?

Doing some more research on that:
https://stackoverflow.com/questions/44887696/repair-normals-on-possibly-bad-stl-files
https://stackoverflow.com/questions/33970843/why-some-stl-models-turn-to-pure-black-in-three-js-scene

**Comment by exilaus** [comment]
there not only nomal issue have face intersection and not mainfold too when create support only good method for cure stl are netfabb services  that cure stl,no think are something we can resolve with js.

no see but the bug of midle slide of layer are resolved?

**Comment by n0sr3v** [comment]
0 layer bug has been fixed (caused by flipping the geometry before start)

I am pretty sure that the so called "not solid stl issue" is related to repairing STL normal's. Broken normal's are known for causing most of the issues.

Pretty sure netfabb also does this.
